language: python
cache: pip
python:
  - "2.7"
  - "3.4"
addons:
  postgresql: "9.4"
services:
  - postgresql
install:
  - "pip install -e ."
  - "pip install -r requirements-dev.txt"
script:
  - flake8
  - py.test
deploy:
  provider: pypi
  user: praekelt.org
  password:
    secure: iVrXchNM+0TcARxt2h99sq+s7i4Qu6wXDwFHgKLh+Xdit7Pd2KH3HK+IyXnT/mtIpo7z4BkvXYakSrI/92iHJVVGSGAtkIQb4ZEOwK5xXaB9K54sz2ADNOKFzyguOfZwpVuUrXlyJUewqcxiQHBiO2wcjBrnfWwwNf9h0/S7DvUw8xSt3pf8RGNkbP7YJwUVxl5Ds0ZSiiVFMaX4ipUSOdljMA11W5vuU0zPkENG6XQ2zkf6uTuD4YCn+xoEVN8g0YGIMxe8LSILXglu+0hmyImbIPR/1l2baIZrGHQIGbtoM1EaF8pnhqvSGWBjYVwyAhCfrkKOqBFvnkCKo6xGvAJ+HbZ1Fq03xVXyttza9fPKDmXPxaa+wHC4BdT1p9+G+l2ARNH1nBdlar+fiV9yjm8Q0+ZH2MwLFAbBlshKIxk7XsdESbe2IXawQFUYFWeCtGLv8JJL/CRAxILIk38fyKjRVFO7wNn9LVYjxCNM2otcBbzX0qqpG2WrKPY8/lXrQzwA0qblvMmv54u6oeo1IQ+Ero+xIU0OBoEPgKT9eBW1h/RDf4ausBVKTCL8hvzdMWBZCiNnStKwuRh5XrcruGb/nAt8daO+GsWHvfNZbm/KHrnXn+s1rLQZSpBv61EEB/be7TIXwZbZCw9sqdiqUfpzVudJlO4giLXO+zV9+yk=
  distributions: sdist bdist_wheel
  on:
    tags: true

matrix:
  include:
    - python: "2.7"
      sudo: required
      dist: trusty
      services: [docker]
      env:
        - IMAGE_NAME=praekeltfoundation/seed-message-sender:develop
        - REGISTRY_USER=praekeltorgdeploy
        - secure: "iVoMNqOJxezbwYlieKloNZo2FT16KwZIH7AkmFs+QMBMY7sHE9TGronMt4YBjFRAVqohFGH2DdtA/Tf7866thdoqlWa7myi3K6JApjREgJg4Mc1GTdrELGNZ3Xx7z3isZdWdEkqMGp/PqCBLFsQL+VgOKfHqMT9YaOf0gf9ceYmjwtzHzlJemqmLVIMe+59wfHFPLuCm4pl9mmscG748FjH4nJn8r5KBrQ+KutKmdn3D4GIFfAAyuqST0Z8LNgOkBblZsUwD4Ah3Z57KrcrSyUaY9K5tP42h4ohJ09H0D4dlNEYfW1WLFZdvyX3tfQTjFF93cKGkwVnIb1Qv1AdxgvoQPSlCkLlW7WOd1sHQGUAK/vXNYzkZxhFRtW+/JXepSEkUgACbItqI45YSbCtdgoZij4I10hVZEobOblo6PK984o8Tcw8Sc7laBp0dUOS0hQBaMvfYyJyLJSnXHPaDqSCu/qnRWx7iWXwBu85szMUrnvnjcU0Dkr721D2FNZF1hUNH2kqBtagwNr3g7rrqNyw+o6LOC/De+c08f5/3kZ4oVg7N7X+FaLQioWXQMg03ny4qXnzLsQt+/If8zpgrtqqjrd+SLWYLcF4PKc25VxsW+a92RT0NkbfUR/WuGppdHtmCtko9qv2v4pQId1NX9ZSEpt8PCINyVjsGyNe58HU="

      # Update docker-engine: we need at least 17.03.1 for `--cache-from`
      install:
        - sudo apt-get update
        - sudo apt-get install -y -o Dpkg::Options::="--force-confold" docker-engine

      before_script:
        - docker pull "$IMAGE_NAME" || true
      script:
        - docker build --tag "$IMAGE_NAME" --cache-from "$IMAGE_NAME" .

      before_deploy:
        - pip install docker-ci-deploy==0.3.0
        - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
      deploy:
        provider: script
        script: dcd --version "$(git rev-parse --short HEAD)" --version-latest "$IMAGE_NAME"
        on:
          branch: develop
