language: python
cache: pip
python:
  - "2.7"
  - "3.4"
addons:
  postgresql: "9.4"
services:
  - postgresql
install:
  - "pip install -e ."
  - "pip install -r requirements-dev.txt"
script:
  - flake8
  - py.test
