language: python
cache: pip
addons:
  postgresql: "9.6"
services:
  - postgresql
install:
  - "pip install -e ."
  - "pip install -r requirements-dev.txt"
before_script:
  - psql -U postgres -c 'create database seed_message_sender;'
script:
  - flake8
  - py.test
  - python manage.py makemigrations | grep 'No changes detected' || (echo 'There are changes which require migrations.' && exit 1)
  - black message_sender seed_message_sender --check
deploy:
  provider: pypi
  user: praekelt.org
  password:
    secure: iVrXchNM+0TcARxt2h99sq+s7i4Qu6wXDwFHgKLh+Xdit7Pd2KH3HK+IyXnT/mtIpo7z4BkvXYakSrI/92iHJVVGSGAtkIQb4ZEOwK5xXaB9K54sz2ADNOKFzyguOfZwpVuUrXlyJUewqcxiQHBiO2wcjBrnfWwwNf9h0/S7DvUw8xSt3pf8RGNkbP7YJwUVxl5Ds0ZSiiVFMaX4ipUSOdljMA11W5vuU0zPkENG6XQ2zkf6uTuD4YCn+xoEVN8g0YGIMxe8LSILXglu+0hmyImbIPR/1l2baIZrGHQIGbtoM1EaF8pnhqvSGWBjYVwyAhCfrkKOqBFvnkCKo6xGvAJ+HbZ1Fq03xVXyttza9fPKDmXPxaa+wHC4BdT1p9+G+l2ARNH1nBdlar+fiV9yjm8Q0+ZH2MwLFAbBlshKIxk7XsdESbe2IXawQFUYFWeCtGLv8JJL/CRAxILIk38fyKjRVFO7wNn9LVYjxCNM2otcBbzX0qqpG2WrKPY8/lXrQzwA0qblvMmv54u6oeo1IQ+Ero+xIU0OBoEPgKT9eBW1h/RDf4ausBVKTCL8hvzdMWBZCiNnStKwuRh5XrcruGb/nAt8daO+GsWHvfNZbm/KHrnXn+s1rLQZSpBv61EEB/be7TIXwZbZCw9sqdiqUfpzVudJlO4giLXO+zV9+yk=
  distributions: sdist bdist_wheel
  on:
    tags: true

matrix:
  include:
    - python: "3.6"
      dist: xenial
      sudo: true
    - python: "3.6"
      dist: xenial
      sudo: true
      services: [docker]
      env:
        - IMAGE_NAME=praekeltfoundation/seed-message-sender:develop
        - REGISTRY_USER=praekeltorgdeploy
        - secure: "DNWcghAFgoSMH0OaHIcK/mKXQAzxSRVRkLDCluEb768NrO/RnTBhoTHUeUM9JMdOrmzkdrG+d2W2MlU/Eqy8+3b/JnOEYgW1i0VAMxlydc3slK9iY3VGAGk58VCbiX59mFONLjK7qU5uJ+pqxu2Xm8dsuTF24CHhJmqbiYstgaU/bYy7lKhF0vkF9lrx7dAhXmj9sdRe8DlOhkvDvj7RFBOI7EtlA9Uef9FZE1pA66HMKdPOCGWZTB8EXfCx1ZPo1SD7Z2p3N/VnPa9bjt4cfT5RnUvBT0exA1nXeAvVepTqfbET2UI1RSLOdvRGjImggQvymAl/TGERMT25oYRbwPyTuG5UPL3hKyZxINMFm/U734tDh351AadVvN/8w6vRPJAh1e74E1WuofbEM29dxxTgONyJltLGvnxLL/GoI8XoLMx+te7eCewP1d3CuQX38gnsWXzWi9Q866H5Wev3BLbkjX+wxYGT579YmdhOpp3NolhgafyY4syI4u6XuX6AyBDXgaKAiiFNQ4VNjDiL4jYYuLln1PYlvCnWLLC0KJxAwYj8icGwlhticz3pBnnqpziDyGwasnwWJgTTfR/RqbRDfkFqzxZ194hSBj/gFtjA5s8rUxG/N5gurEXBaQTlnku6SaiXwQAn/jf3WjO1kQBRyyzqhCrj3aGDwzxaZh8="

      before_script:
        - docker pull "$IMAGE_NAME" || true
      script:
        - docker build --tag "$IMAGE_NAME" --cache-from "$IMAGE_NAME" .

      before_deploy:
        - pip install docker-ci-deploy==0.3.0
        - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
      deploy:
        provider: script
        script: dcd --version "$(git rev-parse --short HEAD)" --version-latest "$IMAGE_NAME"
        on:
          branch: develop

      # Inherited build steps that we don't want
      install: []
      addons: {}
